# -*- coding: utf-8 -*-
"""Code1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6he7QQdP9T2qCIYXqrVFzwXbMXC3u5o
"""

!pip install -q streamlit

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="Institutional Fee Architect",
    page_icon="⚖️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CUSTOM ELEGANT STYLING ---
st.markdown("""
    <style>
    .main {
        background-color: #f8f9fa;
    }
    .stMetric {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        border: 1px solid #eee;
    }
    .stDataFrame {
        border-radius: 10px;
    }
    h1, h2, h3 {
        color: #1e293b;
        font-family: 'Inter', sans-serif;
    }
    .stButton>button {
        width: 100%;
        border-radius: 5px;
        height: 3em;
        background-color: #1e293b;
        color: white;
    }
    </style>
    """, unsafe_allow_html=True)

# --- INITIALIZATION ---
if 'years_count' not in st.session_state:
    st.session_state.years_count = 3

# --- SIDEBAR: DESIGNER CONTROLS ---
with st.sidebar:
    st.title("⚖️ Deal Terms")
    st.markdown("---")

    with st.expander("💼 Capital & Management", expanded=True):
        initial_value = st.number_input("Initial Investment", value=1000000.0, format="%.2f")
        base_mgmt = st.number_input("Mgmt Fee (%)", value=2.0, step=0.1) / 100
        mgmt_basis = st.selectbox("Fee Basis", ["Opening Balance", "Closing Balance"])

    with st.expander("🎯 Performance Incentive", expanded=True):
        base_perf = st.number_input("Perf Fee (%)", value=20.0, step=1.0) / 100
        perf_basis = st.selectbox("Calculation Method", ["Independent", "Net of Management Fee"])
        hurdle_rate = st.number_input("Hurdle Rate (%)", value=8.0, step=0.5) / 100
        hurdle_type = st.radio("Hurdle Style", ["Hard Hurdle", "Soft Hurdle"], horizontal=True)
        use_hwm = st.toggle("High-Water Mark (HWM)", value=True)

    with st.expander("🔬 Sensitivity Range"):
        step_size = st.slider("Step Size (%)", 0.1, 2.0, 0.5) / 100

# --- MAIN INTERFACE ---
st.title("Institutional Performance & Fee Architect")
st.markdown("#### Holistic fund return modeling with sensitivity stress-testing.")

# --- DYNAMIC GROWTH INPUTS ---
with st.container():
    st.write("### 📅 Annual Growth Projections")
    c1, c2, c3 = st.columns([1, 1, 6])
    with c1:
        if st.button("➕ Add Year"): st.session_state.years_count += 1
    with c2:
        if st.button("➖ Remove Year") and st.session_state.years_count > 1: st.session_state.years_count -= 1

    growth_rates = []
    # Grid of 5 columns for inputs
    grid_cols = st.columns(5)
    for i in range(st.session_state.years_count):
        with grid_cols[i % 5]:
            rate = st.number_input(f"Year {i+1} (%)", value=10.0, key=f"g_in_{i}")
            growth_rates.append(rate / 100)

# --- CALCULATION ENGINE ---
def run_model(g_list, m_rate, p_rate):
    curr = initial_value
    hwm = initial_value
    for g in g_list:
        gross_c = curr * (1 + g)
        m_fee = (curr if mgmt_basis == "Opening Balance" else gross_c) * m_rate
        h_amt = curr * hurdle_rate
        threshold = max(hwm, curr + h_amt) if use_hwm else (curr + h_amt)
        compare_val = (gross_c - m_fee) if perf_basis == "Net of Management Fee" else gross_c
        p_fee = 0.0
        if compare_val > threshold:
            if hurdle_type == "Hard Hurdle":
                p_fee = (compare_val - threshold) * p_rate
            else:
                p_pool = compare_val - (hwm if use_hwm else curr)
                p_fee = max(0, p_pool * p_rate)
        curr = gross_c - m_fee - p_fee
        if use_hwm: hwm = max(hwm, curr)
    return curr, hwm

# Execution for Main Results
curr_val = initial_value
hwm_val = initial_value
rows = []
for idx, g in enumerate(growth_rates):
    gross_c = curr_val * (1 + g)
    m_fee = (curr_val if mgmt_basis == "Opening Balance" else gross_c) * base_mgmt
    h_amt = curr_val * hurdle_rate
    threshold = max(hwm_val, curr_val + h_amt) if use_hwm else (curr_val + h_amt)
    compare_val = (gross_c - m_fee) if perf_basis == "Net of Management Fee" else gross_c

    p_fee = 0.0
    if compare_val > threshold:
        if hurdle_type == "Hard Hurdle":
            p_fee = (compare_val - threshold) * base_perf
        else:
            p_pool = compare_val - (hwm_val if use_hwm else curr_val)
            p_fee = max(0, p_pool * base_perf)

    net_val = gross_c - m_fee - p_fee
    rows.append({
        "Year": idx + 1, "Opening Balance": curr_val, "Gross Growth (%)": g*100,
        "Management Fee": m_fee, "Performance Fee": p_fee, "Net Closing": net_val,
        "Watermark": hwm_val if use_hwm else 0
    })
    if use_hwm: hwm_val = max(hwm_val, net_val)
    curr_val = net_val

df_main = pd.DataFrame(rows)

# --- SUMMARY METRICS ---
st.markdown("---")
final_net = df_main["Net Closing"].iloc[-1]
total_fees = df_main["Management Fee"].sum() + df_main["Performance Fee"].sum()
net_cagr = ((final_net / initial_value)**(1/len(growth_rates)) - 1) * 100

m1, m2, m3, m4 = st.columns(4)
m1.metric("Final Net Value", f"${final_net:,.0f}")
m2.metric("Portfolio CAGR", f"{net_cagr:.2f}%")
m3.metric("Total Fees Paid", f"${total_fees:,.0f}")
m4.metric("Fee Leakage", f"{(total_fees/(final_net-initial_value+total_fees))*100:.1f}%" if (final_net-initial_value+total_fees) != 0 else "0%")

# --- VISUALS ---
st.markdown("---")
v1, v2 = st.columns([7, 3])
with v1:
    fig_line = go.Figure()
    fig_line.add_trace(go.Scatter(x=df_main["Year"], y=df_main["Net Closing"], name="Net Asset Value", line=dict(color='#1e293b', width=3), fill='tozeroy'))
    if use_hwm:
        fig_line.add_trace(go.Scatter(x=df_main["Year"], y=df_main["Watermark"], name="High-Water Mark", line=dict(color='#ef4444', dash='dot')))
    fig_line.update_layout(title="Capital Appreciation vs. Watermark", template="simple_white", hovermode="x unified")
    st.plotly_chart(fig_line, use_container_width=True)

with v2:
    fig_pie = px.pie(names=['Net Profit', 'Total Fees'],
                     values=[max(0, final_net - initial_value), total_fees],
                     color_discrete_sequence=['#1e293b', '#94a3b8'], hole=0.6)
    fig_pie.update_layout(title="Alpha Split")
    st.plotly_chart(fig_pie, use_container_width=True)

# --- MAIN TABLE ---
st.write("### 📄 Annual Performance Ledger")
st.dataframe(df_main.style.format(precision=2).background_gradient(subset=["Gross Growth (%)"], cmap="RdYlGn"), use_container_width=True)

# --- SENSITIVITY ---
st.markdown("---")
st.write("### 🎯 Strategic Sensitivity Analysis")
shifts = [-2*step_size, -step_size, 0, step_size, 2*step_size]

c1, c2, c3 = st.columns(3)
def get_cagr_only(g, m, p):
    res, _ = run_model(g, m, p)
    return ((res / initial_value)**(1/len(growth_rates)) - 1) * 100

with c1:
    st.caption("Growth Sensitivity")
    g_sens = pd.DataFrame({"Shift": [f"{s*100:+.1f}%" for s in shifts],
                           "CAGR": [get_cagr_only([x+s for x in growth_rates], base_mgmt, base_perf) for s in shifts]})
    st.dataframe(g_sens.style.format(precision=2).highlight_max(color='#dcfce7').highlight_min(color='#fee2e2'), use_container_width=True)

with c2:
    st.caption("Mgmt Fee Sensitivity")
    m_sens = pd.DataFrame({"Shift": [f"{s*100:+.1f}%" for s in shifts],
                           "CAGR": [get_cagr_only(growth_rates, base_mgmt+s, base_perf) for s in shifts]})
    st.dataframe(m_sens.style.format(precision=2).highlight_max(color='#dcfce7').highlight_min(color='#fee2e2'), use_container_width=True)

with c3:
    st.caption("Perf Fee Sensitivity")
    p_sens = pd.DataFrame({"Shift": [f"{s*100:+.1f}%" for s in shifts],
                           "CAGR": [get_cagr_only(growth_rates, base_mgmt, base_perf+s) for s in shifts]})
    st.dataframe(p_sens.style.format(precision=2).highlight_max(color='#dcfce7').highlight_min(color='#fee2e2'), use_container_width=True)

st.write("#### 3-Way Stress Test: Growth vs. Performance Fee")
matrix = [[get_cagr_only([g+sg for g in growth_rates], base_mgmt, base_perf+sp) for sp in shifts] for sg in shifts]
df_matrix = pd.DataFrame(matrix, index=[f"Growth {s*100:+.1f}%" for s in shifts], columns=[f"Perf {s*100:+.1f}%" for s in shifts])
st.dataframe(df_matrix.style.background_gradient(cmap='RdYlGn').format("{:.2f}%"), use_container_width=True)