# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VRVaNxcOZBQfEBK_BwHcE3F4dapNKgzE
"""

import streamlit as st
import pandas as pd

st.set_page_config(page_title="Investment Fee Simulator", layout="wide")

st.title("Financial Advisor: Fee & CAGR Calculator")
st.markdown("---")

# --- INPUT SECTION ---
with st.sidebar:
    st.header("Parameters")
    initial_value = st.number_input("Initial Value", min_value=0.0, value=1000000.0)

    st.subheader("Fee Structure")
    mgmt_fee_rate = st.number_input("Management Fee (%)", value=2.0) / 100
    mgmt_fee_basis = st.radio("Mgmt Fee Basis", ["Opening Balance", "Closing Balance"])

    perf_fee_rate = st.number_input("Performance Incentive (%)", value=20.0) / 100
    hurdle_rate = st.number_input("Hurdle Rate (%)", value=8.0) / 100
    hurdle_type = st.radio("Hurdle Style", ["Hard Hurdle", "Soft Hurdle"])

    use_hwm = st.checkbox("High-Water Mark (HWM) Applicable", value=True)

# --- DYNAMIC YEAR INPUTS ---
st.subheader("Annual Growth Rates")
if 'years_count' not in st.session_state:
    st.session_state.years_count = 1

col_btn1, col_btn2, _ = st.columns([1, 1, 8])
with col_btn1:
    if st.button("➕ Add Year"):
        st.session_state.years_count += 1
with col_btn2:
    if st.button("➖ Remove") and st.session_state.years_count > 1:
        st.session_state.years_count -= 1

# Input grid for growth rates
growth_rates = []
cols = st.columns(min(st.session_state.years_count, 5)) # Max 5 columns for UI cleanliness
for i in range(st.session_state.years_count):
    idx = i % 5
    with cols[idx]:
        rate = st.number_input(f"Year {i+1} Growth %", value=10.0, key=f"y{i}")
        growth_rates.append(rate / 100)

# --- CALCULATION ENGINE ---
results = []
current_opening = initial_value
hwm_value = initial_value

for i in range(st.session_state.years_count):
    growth = growth_rates[i]
    gross_closing = current_opening * (1 + growth)

    # 1. Management Fee
    if mgmt_fee_basis == "Opening Balance":
        mgmt_fee = current_opening * mgmt_fee_rate
    else:
        mgmt_fee = gross_closing * mgmt_fee_rate
    # 2. Performance Fee Logic
    # Baseline is the amount that must be exceeded before fees kick in
    hurdle_amount = current_opening * hurdle_rate
    target_threshold = max(hwm_value, current_opening + hurdle_amount) if use_hwm else (current_opening + hurdle_amount)

    perf_fee = 0.0
    if gross_closing > target_threshold:
        if hurdle_type == "Hard Hurdle":
            # Fee only on the gain above the threshold
            perf_fee = (gross_closing - target_threshold) * perf_fee_rate
        else:
            # Soft Hurdle: Once hit, fee applies to all gains above HWM/Opening
            catch_up_basis = hwm_value if use_hwm else current_opening
            perf_fee = (gross_closing - catch_up_basis) * perf_fee_rate

    total_fees = mgmt_fee + perf_fee
    net_closing = gross_closing - total_fees
    annual_net_return = (net_closing / current_opening) - 1

    row = {
        "Year": i + 1,
        "Opening Bal": current_opening,
        "Gross Growth %": growth * 100,
        "Gross Closing": gross_closing,
        "Mgmt Fee": mgmt_fee,
        "Perf Fee": perf_fee,
        "Total Fees": total_fees,
        "Net Closing": net_closing,
        "Net Return %": annual_net_return * 100
    }

    if use_hwm:
        row["Watermark"] = hwm_value
        hwm_value = max(hwm_value, net_closing)

    results.append(row)
    current_opening = net_closing

# --- OUTPUTS ---
df = pd.DataFrame(results)
st.subheader("Performance & Fee Table")
st.dataframe(df.style.format(precision=2), use_container_width=True)

# --- CAGR CALCULATION ---
final_net_value = df["Net Closing"].iloc[-1]
years = st.session_state.years_count
cagr = ((final_net_value / initial_value) ** (1 / years)) - 1

st.markdown("---")
res_col1, res_col2 = st.columns(2)
res_col1.metric("Final Value (Net of Fees)", f"${final_net_value:,.2f}")
res_col2.metric("Portfolio CAGR (Net)", f"{cagr*100:.2f}%")

