# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hEF-w06yI8WEq0AzTr9npts_w-laqqYH
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import numpy as np

st.set_page_config(page_title="Institutional Fee & Sensitivity Analytics", layout="wide")

# --- SIDEBAR: CORE DEAL TERMS ---
with st.sidebar:
    st.header("⚙️ Base Case Parameters")
    initial_value = st.number_input("Initial Investment", value=1000000.0)
    base_mgmt = st.number_input("Base Mgmt Fee (%)", value=2.0) / 100
    base_perf = st.number_input("Base Perf Fee (%)", value=20.0) / 100
    base_growth = st.number_input("Avg. Annual Growth (%)", value=10.0) / 100

    st.header("Structure")
    mgmt_basis = st.radio("Mgmt Fee Basis", ["Opening Balance", "Closing Balance"])
    perf_basis = st.radio("Perf Fee Basis", ["Independent", "Net of Mgmt Fee"])
    hurdle_rate = st.number_input("Hurdle Rate (%)", value=8.0) / 100
    use_hwm = st.checkbox("Apply HWM", value=True)
    years = st.slider("Investment Horizon (Years)", 1, 10, 5)

# --- THE CALCULATION ENGINE (REUSABLE FUNCTION) ---
def calc_cagr(g_rate, m_rate, p_rate, initial, yrs, h_rate, m_basis, p_basis, hwm_active):
    current_val = initial
    hwm_val = initial
    for _ in range(yrs):
        gross_c = current_val * (1 + g_rate)
        m_fee = (current_val if m_basis == "Opening Balance" else gross_c) * m_rate

        threshold = max(hwm_val, current_val * (1 + h_rate)) if hwm_active else (current_val * (1 + h_rate))
        compare_val = (gross_c - m_fee) if p_basis == "Net of Mgmt Fee" else gross_c

        p_fee = max(0, (compare_val - threshold) * p_rate) if compare_val > threshold else 0
        current_val = gross_c - m_fee - p_fee
        if hwm_active: hwm_val = max(hwm_val, current_val)

    return ((current_val / initial)**(1/yrs) - 1) * 100

# --- MAIN PAGE ---
st.title("📊 Strategic Fee Sensitivity Analysis")

# --- SECTION 1: INDIVIDUAL ATTRIBUTION ---
st.subheader("1. Individual Variable Impact (CAGR %)")
st.info("How much does a small shift in one variable change your final return?")

shifts = [-0.01, -0.005, 0, 0.005, 0.01]
attr_data = {"Shift": [f"{s*100:+.1f}%" for s in shifts]}

# Calculate individual impacts
attr_data["Var: Growth"] = [calc_cagr(base_growth+s, base_mgmt, base_perf, initial_value, years, hurdle_rate, mgmt_basis, perf_basis, use_hwm) for s in shifts]
attr_data["Var: Mgmt Fee"] = [calc_cagr(base_growth, base_mgmt+s, base_perf, initial_value, years, hurdle_rate, mgmt_basis, perf_basis, use_hwm) for s in shifts]
attr_data["Var: Perf Fee"] = [calc_cagr(base_growth, base_mgmt, base_perf+s, initial_value, years, hurdle_rate, mgmt_basis, perf_basis, use_hwm) for s in shifts]

df_attr = pd.DataFrame(attr_data)
st.table(df_attr.style.format(precision=2).highlight_max(axis=0, color="#2ecc71").highlight_min(axis=0, color="#e74c3c"))

# --- SECTION 2: 2D SENSITIVITY MATRIX ---
st.subheader("2. Growth vs. Performance Fee Sensitivity")
st.write("This table shows CAGR based on varying Growth (Rows) and Performance Fees (Columns).")

# Rows = Growth, Cols = Perf Fee
rows_growth = [base_growth + s for s in shifts]
cols_perf = [base_perf + s for s in shifts]

matrix = []
for g in rows_growth:
    row = []
    for p in cols_perf:
        row.append(calc_cagr(g, base_mgmt, p, initial_value, years, hurdle_rate, mgmt_basis, perf_basis, use_hwm))
    matrix.append(row)

df_matrix = pd.DataFrame(
    matrix,
    index=[f"Growth {g*100:.1f}%" for g in rows_growth],
    columns=[f"Perf Fee {p*100:.1f}%" for p in cols_perf]
)

st.dataframe(df_matrix.style.background_gradient(cmap='RdYlGn').format("{:.2f}%"))

# --- SECTION 3: VISUALIZING THE SENSITIVITY ---
fig = go.Figure(data=[go.Surface(z=df_matrix.values, x=shifts, y=shifts)])
fig.update_layout(title='3D Risk Surface: Growth & Perf Fee Impact on CAGR',
                  scene=dict(xaxis_title='Perf Fee Shift', yaxis_title='Growth Shift', zaxis_title='CAGR %'))
st.plotly_chart(fig, use_container_width=True)